apiVersion: v1
kind: PersistentVolumeClaim # volume attached to pod, that master will provision and attach to pod
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:
        - ReadWriteOnce #Can be used by a single node
    resources:
        requests:
            storage: 2Gi 